/**
 * PW GRAPH
 * This is a sample server graph server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_OAINodeApiHandler_H
#define OAI_OAINodeApiHandler_H

#include <QObject>

#include "OAINode.h"
#include <QString>

namespace OpenAPI {

class OAINodeApiHandler : public QObject
{
    Q_OBJECT

public:
    OAINodeApiHandler();
    virtual ~OAINodeApiHandler();


public slots:
    virtual void addCustomNode(OAINode body);
    virtual void addNodeParameter(qint64 node_id, QString name, QString parameter_type, QString parameter_value);
    virtual void addNodeTrigger(qint64 node_id, QString target_parameter, QString trigger_type, qint64 trigger_index, qint64 target_node_id);
    virtual void addTemplateNode(OAINode body);
    virtual void deleteNode(qint64 node_id, QString api_key);
    virtual void editNodeParameter(qint64 node_id, QString name, QString parameter_value);
    virtual void findNodesByStatus(QList<QString> status);
    virtual void getNodeById(qint64 node_id);
    virtual void nodesGet();
    

};

}

#endif // OAI_OAINodeApiHandler_H
