/**
 * PW GRAPH
 * This is a sample server graph server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAINode.h
 *
 * 
 */

#ifndef OAINode_H
#define OAINode_H

#include <QJsonObject>

#include "OAIParameter.h"
#include "OAIRelation.h"
#include <QList>
#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAINode : public OAIObject {
public:
    OAINode();
    OAINode(QString json);
    ~OAINode() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint64 getNodeId() const;
    void setNodeId(const qint64 &node_id);
    bool is_node_id_Set() const;
    bool is_node_id_Valid() const;

    QString getStatus() const;
    void setStatus(const QString &status);
    bool is_status_Set() const;
    bool is_status_Valid() const;

    QList<OAIParameter> getParameters() const;
    void setParameters(const QList<OAIParameter> &parameters);
    bool is_parameters_Set() const;
    bool is_parameters_Valid() const;

    QList<OAIRelation> getRelations() const;
    void setRelations(const QList<OAIRelation> &relations);
    bool is_relations_Set() const;
    bool is_relations_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint64 node_id;
    bool m_node_id_isSet;
    bool m_node_id_isValid;

    QString status;
    bool m_status_isSet;
    bool m_status_isValid;

    QList<OAIParameter> parameters;
    bool m_parameters_isSet;
    bool m_parameters_isValid;

    QList<OAIRelation> relations;
    bool m_relations_isSet;
    bool m_relations_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAINode)

#endif // OAINode_H
