/**
 * PW GRAPH
 * This is a sample server graph server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIParameter.h
 *
 * 
 */

#ifndef OAIParameter_H
#define OAIParameter_H

#include <QJsonObject>

#include <QString>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIParameter : public OAIObject {
public:
    OAIParameter();
    OAIParameter(QString json);
    ~OAIParameter() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint64 getParameterId() const;
    void setParameterId(const qint64 &parameter_id);
    bool is_parameter_id_Set() const;
    bool is_parameter_id_Valid() const;

    QString getParameterName() const;
    void setParameterName(const QString &parameter_name);
    bool is_parameter_name_Set() const;
    bool is_parameter_name_Valid() const;

    QString getParameterType() const;
    void setParameterType(const QString &parameter_type);
    bool is_parameter_type_Set() const;
    bool is_parameter_type_Valid() const;

    QString getParameterValue() const;
    void setParameterValue(const QString &parameter_value);
    bool is_parameter_value_Set() const;
    bool is_parameter_value_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint64 parameter_id;
    bool m_parameter_id_isSet;
    bool m_parameter_id_isValid;

    QString parameter_name;
    bool m_parameter_name_isSet;
    bool m_parameter_name_isValid;

    QString parameter_type;
    bool m_parameter_type_isSet;
    bool m_parameter_type_isValid;

    QString parameter_value;
    bool m_parameter_value_isSet;
    bool m_parameter_value_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIParameter)

#endif // OAIParameter_H
