/**
 * PW GRAPH
 * This is a sample server graph server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIRelation.h
 *
 * 
 */

#ifndef OAIRelation_H
#define OAIRelation_H

#include <QJsonObject>

#include "OAIAction.h"
#include "OAIParameter.h"
#include "OAITrigger.h"
#include <QList>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIRelation : public OAIObject {
public:
    OAIRelation();
    OAIRelation(QString json);
    ~OAIRelation() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint64 getRelationId() const;
    void setRelationId(const qint64 &relation_id);
    bool is_relation_id_Set() const;
    bool is_relation_id_Valid() const;

    QList<OAITrigger> getTriggers() const;
    void setTriggers(const QList<OAITrigger> &triggers);
    bool is_triggers_Set() const;
    bool is_triggers_Valid() const;

    QList<OAIAction> getActions() const;
    void setActions(const QList<OAIAction> &actions);
    bool is_actions_Set() const;
    bool is_actions_Valid() const;

    QList<OAIParameter> getInternalParameters() const;
    void setInternalParameters(const QList<OAIParameter> &internal_parameters);
    bool is_internal_parameters_Set() const;
    bool is_internal_parameters_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint64 relation_id;
    bool m_relation_id_isSet;
    bool m_relation_id_isValid;

    QList<OAITrigger> triggers;
    bool m_triggers_isSet;
    bool m_triggers_isValid;

    QList<OAIAction> actions;
    bool m_actions_isSet;
    bool m_actions_isValid;

    QList<OAIParameter> internal_parameters;
    bool m_internal_parameters_isSet;
    bool m_internal_parameters_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIRelation)

#endif // OAIRelation_H
