/**
 * PW GRAPH
 * This is a sample server graph server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIView.h
 *
 * 
 */

#ifndef OAIView_H
#define OAIView_H

#include <QJsonObject>

#include "OAIParameter.h"
#include <QList>

#include "OAIEnum.h"
#include "OAIObject.h"

namespace OpenAPI {

class OAIView : public OAIObject {
public:
    OAIView();
    OAIView(QString json);
    ~OAIView() override;

    QString asJson() const override;
    QJsonObject asJsonObject() const override;
    void fromJsonObject(QJsonObject json) override;
    void fromJson(QString jsonString) override;

    qint64 getViewId() const;
    void setViewId(const qint64 &view_id);
    bool is_view_id_Set() const;
    bool is_view_id_Valid() const;

    QList<OAIParameter> getFilterParameters() const;
    void setFilterParameters(const QList<OAIParameter> &filter_parameters);
    bool is_filter_parameters_Set() const;
    bool is_filter_parameters_Valid() const;

    virtual bool isSet() const override;
    virtual bool isValid() const override;

private:
    void initializeModel();

    qint64 view_id;
    bool m_view_id_isSet;
    bool m_view_id_isValid;

    QList<OAIParameter> filter_parameters;
    bool m_filter_parameters_isSet;
    bool m_filter_parameters_isValid;
};

} // namespace OpenAPI

Q_DECLARE_METATYPE(OpenAPI::OAIView)

#endif // OAIView_H
