<?php

/**
 * PW GRAPH
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * This is a sample server graph server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Api\GraphApi;

/**
 * GraphApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\GraphApi
 */
class GraphApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addCustomGraph
     *
     * Add a new custom graph.
     *
     * @covers ::addCustomGraph
     */
    public function testAddCustomGraph()
    {
        $this->markTestIncomplete(
            'Test of "addCustomGraph" method has not been implemented yet.'
        );
    }

    /**
     * Test case for addFilterView
     *
     * Edit graph filter view.
     *
     * @covers ::addFilterView
     */
    public function testAddFilterView()
    {
        $this->markTestIncomplete(
            'Test of "addFilterView" method has not been implemented yet.'
        );
    }

    /**
     * Test case for addGraphParameter
     *
     * Adds a new global parameter to the graph.
     *
     * @covers ::addGraphParameter
     */
    public function testAddGraphParameter()
    {
        $this->markTestIncomplete(
            'Test of "addGraphParameter" method has not been implemented yet.'
        );
    }

    /**
     * Test case for addTemplateGraph
     *
     * Add a new template graph.
     *
     * @covers ::addTemplateGraph
     */
    public function testAddTemplateGraph()
    {
        $this->markTestIncomplete(
            'Test of "addTemplateGraph" method has not been implemented yet.'
        );
    }

    /**
     * Test case for deleteGraph
     *
     * Deletes a graph.
     *
     * @covers ::deleteGraph
     */
    public function testDeleteGraph()
    {
        $this->markTestIncomplete(
            'Test of "deleteGraph" method has not been implemented yet.'
        );
    }

    /**
     * Test case for editGraphParameter
     *
     * Updates a global parameter.
     *
     * @covers ::editGraphParameter
     */
    public function testEditGraphParameter()
    {
        $this->markTestIncomplete(
            'Test of "editGraphParameter" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getGraphById
     *
     * Find graph by ID.
     *
     * @covers ::getGraphById
     */
    public function testGetGraphById()
    {
        $this->markTestIncomplete(
            'Test of "getGraphById" method has not been implemented yet.'
        );
    }

    /**
     * Test case for graphsGet
     *
     * Show user's graphs.
     *
     * @covers ::graphsGet
     */
    public function testGraphsGet()
    {
        $this->markTestIncomplete(
            'Test of "graphsGet" method has not been implemented yet.'
        );
    }
}
