<?php

/**
 * PW GRAPH
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * This is a sample server graph server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Api\NodeApi;

/**
 * NodeApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\NodeApi
 */
class NodeApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addCustomNode
     *
     * Add a custom node to the graph.
     *
     * @covers ::addCustomNode
     */
    public function testAddCustomNode()
    {
        $this->markTestIncomplete(
            'Test of "addCustomNode" method has not been implemented yet.'
        );
    }

    /**
     * Test case for addNodeParameter
     *
     * Adds a new parameter to the node.
     *
     * @covers ::addNodeParameter
     */
    public function testAddNodeParameter()
    {
        $this->markTestIncomplete(
            'Test of "addNodeParameter" method has not been implemented yet.'
        );
    }

    /**
     * Test case for addNodeTrigger
     *
     * Add node trigger.
     *
     * @covers ::addNodeTrigger
     */
    public function testAddNodeTrigger()
    {
        $this->markTestIncomplete(
            'Test of "addNodeTrigger" method has not been implemented yet.'
        );
    }

    /**
     * Test case for addTemplateNode
     *
     * Add template node to the graph.
     *
     * @covers ::addTemplateNode
     */
    public function testAddTemplateNode()
    {
        $this->markTestIncomplete(
            'Test of "addTemplateNode" method has not been implemented yet.'
        );
    }

    /**
     * Test case for deleteNode
     *
     * Deletes a node.
     *
     * @covers ::deleteNode
     */
    public function testDeleteNode()
    {
        $this->markTestIncomplete(
            'Test of "deleteNode" method has not been implemented yet.'
        );
    }

    /**
     * Test case for editNodeParameter
     *
     * Updates a node parameter.
     *
     * @covers ::editNodeParameter
     */
    public function testEditNodeParameter()
    {
        $this->markTestIncomplete(
            'Test of "editNodeParameter" method has not been implemented yet.'
        );
    }

    /**
     * Test case for findNodesByStatus
     *
     * Finds node by status.
     *
     * @covers ::findNodesByStatus
     */
    public function testFindNodesByStatus()
    {
        $this->markTestIncomplete(
            'Test of "findNodesByStatus" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getNodeById
     *
     * Find node by ID.
     *
     * @covers ::getNodeById
     */
    public function testGetNodeById()
    {
        $this->markTestIncomplete(
            'Test of "getNodeById" method has not been implemented yet.'
        );
    }

    /**
     * Test case for nodesGet
     *
     * Show nodes in the selected graph.
     *
     * @covers ::nodesGet
     */
    public function testNodesGet()
    {
        $this->markTestIncomplete(
            'Test of "nodesGet" method has not been implemented yet.'
        );
    }
}
