<?php

/**
 * PW GRAPH
 * PHP version 7.4
 *
 * @package OpenAPIServer
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 */

/**
 * This is a sample server graph server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.
 * The version of the OpenAPI document: 1.0.0
 * Contact: apiteam@swagger.io
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

/**
 * NOTE: This class is auto generated by the openapi generator program.
 * https://github.com/openapitools/openapi-generator
 * Please update the test case below to test the endpoint.
 */
namespace OpenAPIServer\Api;

use PHPUnit\Framework\TestCase;
use OpenAPIServer\Api\UserApi;

/**
 * UserApiTest Class Doc Comment
 *
 * @package OpenAPIServer\Api
 * @author  OpenAPI Generator team
 * @link    https://github.com/openapitools/openapi-generator
 *
 * @coversDefaultClass \OpenAPIServer\Api\UserApi
 */
class UserApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createUser
     *
     * Create user.
     *
     * @covers ::createUser
     */
    public function testCreateUser()
    {
        $this->markTestIncomplete(
            'Test of "createUser" method has not been implemented yet.'
        );
    }

    /**
     * Test case for deleteUser
     *
     * Delete user.
     *
     * @covers ::deleteUser
     */
    public function testDeleteUser()
    {
        $this->markTestIncomplete(
            'Test of "deleteUser" method has not been implemented yet.'
        );
    }

    /**
     * Test case for getUserByName
     *
     * Get user by user name.
     *
     * @covers ::getUserByName
     */
    public function testGetUserByName()
    {
        $this->markTestIncomplete(
            'Test of "getUserByName" method has not been implemented yet.'
        );
    }

    /**
     * Test case for loginUser
     *
     * Logs user into the system.
     *
     * @covers ::loginUser
     */
    public function testLoginUser()
    {
        $this->markTestIncomplete(
            'Test of "loginUser" method has not been implemented yet.'
        );
    }

    /**
     * Test case for logoutUser
     *
     * Logs out current logged in user session.
     *
     * @covers ::logoutUser
     */
    public function testLogoutUser()
    {
        $this->markTestIncomplete(
            'Test of "logoutUser" method has not been implemented yet.'
        );
    }

    /**
     * Test case for updateUser
     *
     * Updated user.
     *
     * @covers ::updateUser
     */
    public function testUpdateUser()
    {
        $this->markTestIncomplete(
            'Test of "updateUser" method has not been implemented yet.'
        );
    }
}
